baseURL = "https://riccardocorna.github.io"
languageCode = "it-it"
title = "IT Specialist Cloud"
theme = "ananke"

DefaultContentLanguage = "it"
#SectionPagesMenu = "main"
Paginate = 6 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = false

[languages]
  [languages.it]
    title = "IT Specialist Cloud"
    weight = 1
    contentDir = "content/it"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[taxonomies]
  category = "categories"
  tag = "tags"

[permalinks]
  blog = "/:title/"

[menu]
[[menu.main]]
  identifier = "about"
  name = "whoami"
  url = "/about"
  weight = 2
[[menu.main]]
  identifier = "eventi-community"
  name = "eventi"
  url = "/categories/eventi-community"
  weight = 3
[[menu.main]]
  identifier = "identity-security"
  name = "identity & security"
  url = "/categories/identity-security"
  weight = 4
[[menu.main]]
  identifier = "modern-endpoint"
  name = "modern endpoint"
  url = "/categories/modern-endpoint"
  weight = 5
[[menu.main]]
  identifier = "cloud-datacenter"
  name = "cloud datacenter"
  url = "/categories/cloud-datacenter"
  weight = 6
[[menu.main]]
  identifier = "altro"
  name = "altro"
  url = "/categories/altro"
  weight = 7
[[menu.main]]
  identifier = "divagazioni"
  name = "divagazioni"
  url = "/categories/divagazioni"
  weight = 8
  [[menu.main]]
  identifier = "archivio"
  name = "archivio"
  url = "/categories/archivio"
  weight = 9
[[menu.main]]
  identifier = "privacy-policy"
  name = "privacy policy"
  url = "https://www.iubenda.com/privacy-policy/37879840"
  weight = 10

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  #body_classes = "sans-serif bg-near-white"
  #post_content_classes = "serif"
  background_color_class = "bg-black"
  recent_posts_number = 3
  show_reading_time = true

[[params.ananke_socials]]
name = "linkedin"
url = "https://linkedin.com/in/riccardocorna/it"

[[params.ananke_socials]]
name = "youtube"
url = "https://youtube.com/@ITSpecialistCloud"

[[params.ananke_socials]]
name = "mastodon"
url = "https://mastodon.uno/@riccardocorna"
color = "#595AFF"

[[params.ananke_socials]]
name = "ko-fi"
url = "https://ko-fi.com/riccardocorna"
color = "#00B0F1"